services:
  frontend:
    image: getcold/234-deploylab-frontend:latest
    pull_policy: always
    ports:
      - "8081:8080"
    environment:
      - VITE_GRAPHQL_URI=http://35.175.202.63:8083/graphql
      - VITE_SERVER_URI=http://35.175.202.63:8083
    restart: unless-stopped